version: '3.6'
services:
  server:
    build:
      context: ./build
      target: plutus-playground
    image: plutus-playground
    ports:
      - '8080:8080'
    command:
      - 'cd plutus-playground-client && plutus-playground-server'
  client:
    image: plutus-playground
    command:
      - 'cd plutus-playground-client && npm run start'
    depends_on:
      - server
    ports:
      - '8009:8009'
    links:
      - server
  docs:
    build:
      context: ./build
      target: plutus-docs
    image: plutus-docs
    ports:
      - '8002:8002'
    command:
      - 'build-and-serve-docs'
  haddock:
        build:
          context: ./build
          target: plutus-haddock
        image: plutus-haddock
        ports:
          - '8081:8081'
        command:
          - 'cd /opt/plutus-haddock && ./plutus-haddock -s ./result'

