version: '3.6'
services:
  haddock:
    build:
      context: ./build
      target: plutus-haddock
    image: plutus-haddock
    ports:
      - '8081:80'
  docs:
    build:
      context: ./build
      target: cardano-docs
    image: cardano-docs
    ports:
      - '8002:80'
